apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quix-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_USERNAME/YOUR_REPO
    targetRevision: main
    path: k8s-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
