apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quix-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: quix.quixly.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quix-service
            port:
              number: 80
